// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePDF() {
  return window['go']['pdf']['PDFService']['ClosePDF']();
}

export function GenerateThumbnail(arg1, arg2) {
  return window['go']['pdf']['PDFService']['GenerateThumbnail'](arg1, arg2);
}

export function GetMetadata() {
  return window['go']['pdf']['PDFService']['GetMetadata']();
}

export function GetPageCount() {
  return window['go']['pdf']['PDFService']['GetPageCount']();
}

export function GetPageDimensions(arg1) {
  return window['go']['pdf']['PDFService']['GetPageDimensions'](arg1);
}

export function OpenPDF() {
  return window['go']['pdf']['PDFService']['OpenPDF']();
}

export function OpenPDFByPath(arg1) {
  return window['go']['pdf']['PDFService']['OpenPDFByPath'](arg1);
}

export function RenderPage(arg1, arg2) {
  return window['go']['pdf']['PDFService']['RenderPage'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['pdf']['PDFService']['Startup'](arg1);
}
