// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';
import {context} from '../models';

export function ClosePDF():Promise<void>;

export function GetMetadata():Promise<pdf.PDFMetadata>;

export function GetPageCount():Promise<number>;

export function OpenPDF():Promise<pdf.PDFMetadata>;

export function OpenPDFByPath(arg1:string):Promise<pdf.PDFMetadata>;

export function RenderPage(arg1:number,arg2:number):Promise<pdf.PageInfo>;

export function Startup(arg1:context.Context):Promise<void>;
