// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecent(arg1, arg2) {
  return window['go']['pdf']['RecentFilesService']['AddRecent'](arg1, arg2);
}

export function ClearRecent() {
  return window['go']['pdf']['RecentFilesService']['ClearRecent']();
}

export function GetRecent() {
  return window['go']['pdf']['RecentFilesService']['GetRecent']();
}

export function Startup(arg1) {
  return window['go']['pdf']['RecentFilesService']['Startup'](arg1);
}
