// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';
import {context} from '../models';

export function AddRecent(arg1:string,arg2:number):Promise<void>;

export function ClearRecent():Promise<void>;

export function GetRecent():Promise<Array<pdf.RecentFile>>;

export function Startup(arg1:context.Context):Promise<void>;
