// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['config']['Service']['Get']();
}

export function Load() {
  return window['go']['config']['Service']['Load']();
}

export function Reset() {
  return window['go']['config']['Service']['Reset']();
}

export function Save() {
  return window['go']['config']['Service']['Save']();
}

export function Update(arg1) {
  return window['go']['config']['Service']['Update'](arg1);
}
