// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Get():Promise<config.Config>;

export function Load():Promise<void>;

export function Reset():Promise<void>;

export function Save():Promise<void>;

export function Update(arg1:config.Config):Promise<void>;
