// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListCertificates() {
  return window['go']['signature']['SignatureService']['ListCertificates']();
}

export function ListCertificatesFiltered(arg1) {
  return window['go']['signature']['SignatureService']['ListCertificatesFiltered'](arg1);
}

export function SearchCertificates(arg1) {
  return window['go']['signature']['SignatureService']['SearchCertificates'](arg1);
}

export function SignPDF(arg1, arg2, arg3) {
  return window['go']['signature']['SignatureService']['SignPDF'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['signature']['SignatureService']['Startup'](arg1);
}

export function VerifySignature(arg1) {
  return window['go']['signature']['SignatureService']['VerifySignature'](arg1);
}
