// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {signature} from '../models';
import {context} from '../models';

export function ListCertificates():Promise<Array<signature.Certificate>>;

export function SignPDF(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function VerifySignature(arg1:string):Promise<Array<signature.SignatureInfo>>;
