// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {signature} from '../models';
import {context} from '../models';

export function AddCertificateStore(arg1:string):Promise<void>;

export function AddTokenLibrary(arg1:string):Promise<void>;

export function DeleteSignatureProfile(arg1:string):Promise<void>;

export function GetDefaultCertificateSources():Promise<Record<string, Array<string>>>;

export function GetDefaultSignatureProfile():Promise<signature.SignatureProfile>;

export function GetDefaultTokenLibraries():Promise<Array<string>>;

export function GetSignatureProfile(arg1:string):Promise<signature.SignatureProfile>;

export function ListCertificates():Promise<Array<signature.Certificate>>;

export function ListCertificatesFiltered(arg1:signature.CertificateFilter):Promise<Array<signature.Certificate>>;

export function ListSignatureProfiles():Promise<Array<signature.SignatureProfile>>;

export function RemoveCertificateStore(arg1:string):Promise<void>;

export function RemoveTokenLibrary(arg1:string):Promise<void>;

export function SaveSignatureProfile(arg1:signature.SignatureProfile):Promise<void>;

export function SearchCertificates(arg1:string):Promise<Array<signature.Certificate>>;

export function SignPDF(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SignPDFWithProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SignPDFWithProfileAndPosition(arg1:string,arg2:string,arg3:string,arg4:string,arg5:signature.SignaturePosition):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function VerifySignature(arg1:string):Promise<Array<signature.SignatureInfo>>;
