// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCertificateStore(arg1) {
  return window['go']['signature']['SignatureService']['AddCertificateStore'](arg1);
}

export function AddTokenLibrary(arg1) {
  return window['go']['signature']['SignatureService']['AddTokenLibrary'](arg1);
}

export function DeleteSignatureProfile(arg1) {
  return window['go']['signature']['SignatureService']['DeleteSignatureProfile'](arg1);
}

export function GetDefaultCertificateSources() {
  return window['go']['signature']['SignatureService']['GetDefaultCertificateSources']();
}

export function GetDefaultSignatureProfile() {
  return window['go']['signature']['SignatureService']['GetDefaultSignatureProfile']();
}

export function GetDefaultTokenLibraries() {
  return window['go']['signature']['SignatureService']['GetDefaultTokenLibraries']();
}

export function GetSignatureProfile(arg1) {
  return window['go']['signature']['SignatureService']['GetSignatureProfile'](arg1);
}

export function ListCertificates() {
  return window['go']['signature']['SignatureService']['ListCertificates']();
}

export function ListCertificatesFiltered(arg1) {
  return window['go']['signature']['SignatureService']['ListCertificatesFiltered'](arg1);
}

export function ListSignatureProfiles() {
  return window['go']['signature']['SignatureService']['ListSignatureProfiles']();
}

export function RemoveCertificateStore(arg1) {
  return window['go']['signature']['SignatureService']['RemoveCertificateStore'](arg1);
}

export function RemoveTokenLibrary(arg1) {
  return window['go']['signature']['SignatureService']['RemoveTokenLibrary'](arg1);
}

export function SaveSignatureProfile(arg1) {
  return window['go']['signature']['SignatureService']['SaveSignatureProfile'](arg1);
}

export function SearchCertificates(arg1) {
  return window['go']['signature']['SignatureService']['SearchCertificates'](arg1);
}

export function SignPDF(arg1, arg2, arg3) {
  return window['go']['signature']['SignatureService']['SignPDF'](arg1, arg2, arg3);
}

export function SignPDFWithProfile(arg1, arg2, arg3, arg4) {
  return window['go']['signature']['SignatureService']['SignPDFWithProfile'](arg1, arg2, arg3, arg4);
}

export function SignPDFWithProfileAndPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['signature']['SignatureService']['SignPDFWithProfileAndPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function Startup(arg1) {
  return window['go']['signature']['SignatureService']['Startup'](arg1);
}

export function VerifySignature(arg1) {
  return window['go']['signature']['SignatureService']['VerifySignature'](arg1);
}
