// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;
